### ISSUE TITLE
render() got an unexpected keyword argument 'template_pack'

### ISSUE THREAD

**Issue by naveensingh** [django-crispy-forms/django-crispy-forms#586] opened 2016-05-06 04:18 UTC
Hi there,

I recently upgraded one of my projects to Django 1.9.5 as a part of it, I upgraded Crispy forms to latest version 1.6.0 and since then all my crispy forms through an error.

`render() got an unexpected keyword argument 'template_pack'`

I downgraded crispy forms to a version below but that didn't seem to help. 

To fix the issue I edited the **crispy_forms/utils.py line 73** which had the extra argument "template_pack". I removed the argument and it all worked fine. Not sure if I am doing something wrong with my form or is it version incompatibility. For now this did fix the issue but I needed to know if anyone else is having this issue and is there a better fix for something like this.

I'm attaching an example form and the error that I got. Any help is appreciated.

**Form:**

![form](https://cloud.githubusercontent.com/assets/5666725/15064177/39ccaed6-136f-11e6-92c8-d1167017710d.png)

---

**Error:**

![error](https://cloud.githubusercontent.com/assets/5666725/15064181/426d0b58-136f-11e6-939f-278288dd7f58.png)

**Comment by carltongibson** [comment] 2016-05-06 06:51
@naveensingh Thanks for the report. A good place to start would be to run the test suite and see what breaks with the change. (A PR would have the tests run automatically.)

**Comment by naveensingh** [comment] 2016-05-06 08:31
@carltongibson Sure thanks i'll try and run the test.

**Comment by belugame** [comment] 2016-09-07 08:22
@naveensingh I'm facing the same problem after going to crispy-forms 1.6 from 1.4 on Django 1.8. Did you remain with 1.6?

Someone else also ran into the error here: https://github.com/sshwsfc/xadmin/issues/301

**Comment by pilgrim2go** [comment] 2016-11-03 09:28
I follow the doc 
```https://ana-balica.github.io/2014/11/04/the-tale-of-dry-with-django-crispy-forms/```
and got the same issue

**Comment by zoidbergwill** [comment] 2016-11-07 08:16
It's strange that this isn't covered by the tests. 

Would any of you be willing to add tests and the fix @naveensingh suggested?

**Comment by carltongibson** [comment] 2017-02-21 15:12
I'm going to close this as I cannot reproduce it. If someone can provide a failing test case I am happy to re-open it. 

The stack trace doesn't make sense as is — `render_field` calls `render` on a `Layout` object passing the `template_pack` parameter. That is unchanged between 1.4 (and before) and now. Therefore I cannot see how the issue arrises. 

The linked `xadmin` issue has the right solution: ensure your custom layout objects accept the `template_packs` parameter. 

Again: happy to look at a fresh issue that actually provides steps to reproduce.

**Closed by carltongibson** 2017-02-21 15:12 UTC
Labels: Bug

**Comment by ImanoWilliams** [comment] 2021-12-31 01:56
I recently upgraded to the latest crispy form and upgraded to Django 4.0 running on Python 3.10. Since then I am getting "RenderableMixin.render() got an unexpected keyword argument 'template_pack'" when I have {% crispy form %} in my .html template file.

**Comment by smithdc1** [comment] 2021-12-31 06:33
Hi @ImanoWilliams 

Are you able to provide a small reproducible example of this? 

There's lots of methods called render in Django. The method you pointed at in utils is `render_field` and therefore is about rendering a field whereas the new methods in Django 4.0 are about rendering forms. I'm therefore not immediately sure why this would be causing an issue.

**Comment by ImanoWilliams** [comment] 2021-12-31 12:59
Hi @smithdc1 ,

Here is the form class

```
class UseCaseProfileForm(ModelForm):
    class Meta:
        model = UseCaseProfile
        exclude = ('project', 'useCaseRelative', 'useCaseSupportedRole', 'nextQualifiedUseCase', 'conflictedUseCase',
                   'verifiedUseCase')

    useCaseName = forms.CharField(label='Name', widget=forms.TextInput(
        attrs={'placeholder': 'Login'}))
    useCaseBoundary = forms.ChoiceField(label='Boundary', widget=forms.Select, choices=BOUNDARY_CHOICES)
    useCasePurpose = forms.ChoiceField(label='Purpose', widget=forms.Select, choices=PURPOSE_CHOICES)
    useCaseInteraction = forms.ChoiceField(label='Interaction', widget=forms.Select, choices=INTERACTION_CHOICES)

    def __init__(self, *args, **kwargs):
        super(UseCaseProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        FormHelper.form_tag = False
        self.helper.layout = Layout(self,
                                    Row(Column('useCaseName', css_class='form-group col-md-5 mb-0'),
                                        Column('useCaseBoundary', css_class='form-group col-md-2 mb-0'),
                                        Column('useCasePurpose', css_class='form-group col-md-2 mb-0'),
                                        Column('useCaseInteraction', css_class='form-group col-md-3 mb-0'),
                                        css_class='form-row'))
```

Here is the view class

```
class UseCaseCreateView(LoginRequiredMixin, CreateView):
    template_name = "useCaseExtract/useCaseCreate.html"
    form_class = UseCaseProfileForm
    model = UseCaseProfile
    object = None

    def get(self, request, *args, **kwargs):
        user = self.request.user
        projectList = Project.objects.filter(user=user)
        currentProject = projectList.filter(projectName=self.kwargs['project'])
        actorList = currentProject[0].supportedrole_set.all()
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        return self.render_to_response(self.get_context_data(form=form))#,


    def post(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        useCaseProf = form.save(commit=False)
        project = Project.objects.get(user=self.request.user, projectName=self.kwargs['project'])
        useCaseProf.project = project
        useCaseProf.save()
        print(useCaseProf.id)
        success_url = None
        if 'create' in self.request.POST:
            success_url = reverse_lazy('useCaseExtract:UseCaseList',
                                       kwargs={'project': self.kwargs['project']})
        elif 'createNew' in self.request.POST:
            success_url = reverse_lazy('useCaseExtract:UseCaseCreate',
                                       kwargs={'project': self.kwargs['project']})
        return HttpResponseRedirect(success_url)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))
```
Here is the template:
```
<div class="card">
        <div class="card-body bg-info">
        <form method="POST" enctype="multipart/form-data" style="margin-left: 40px; margin-right: 40px" >
        {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
            {% endfor %}
            {% csrf_token %}
            <div class="card">
                <h4 class="card-header"> General Use Case Information</h4>
                <div class="card-body">
            <fieldset>
                {{ form.management_form }}
                {{ form.non_form_errors }}
                   {% crispy form%}
            </fieldset>

                </div>
            </div>

        </div>
            <div class="card-footer bg-secondary text-center">
                <a href="{% url 'useCaseExtract:UseCaseList' view.kwargs.project %}" class="btn btn-danger" role="button" > {% icon "arrow-alt-circle-left" %}</a>
                <button type="submit" class="btn btn-success" name="create">
                                {% icon 'save' %}
                </button>
                <button type="submit" class="btn btn-success" name="createNew">
                                {% icon 'save' %} & {% icon 'plus' %} Another
                </button>
            </div>
        </form>
    </div>
    </div>
```

Here is a sample of the stack trace error:
  ```
File "...path_to_...\venv\lib\site-packages\crispy_forms\templatetags\crispy_forms_tags.py", line 204, in render
    c = self.get_render(context).flatten()
  File "...path_to_...\venv\lib\site-packages\crispy_forms\templatetags\crispy_forms_tags.py", line 120, in get_render
    actual_form.form_html = helper.render_layout(
  File "...path_to_...\venv\lib\site-packages\crispy_forms\helper.py", line 301, in render_layout
    html = self.layout.render(form, self.form_style, context, template_pack=template_pack)
  File "...path_to_...\venv\lib\site-packages\crispy_forms\layout.py", line 135, in render
    return self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "...path_to_...\venv\lib\site-packages\crispy_forms\layout.py", line 96, in get_rendered_fields
    return "".join(
  File "...path_to_...\venv\lib\site-packages\crispy_forms\layout.py", line 97, in <genexpr>
    render_field(field, form, form_style, context, template_pack=template_pack, **kwargs)
  File "...path_to_...\venv\lib\site-packages\crispy_forms\utils.py", line 66, in render_field
    return field.render(form, form_style, context, template_pack=template_pack)
TypeError: RenderableMixin.render() got an unexpected keyword argument 'template_pack'
```
Based on the stacks trace, I added a print out of the self.fields in method, get_rendered_fields, defined in layouts.py. I got this **[<UseCaseProfileForm bound=False, valid=Unknown, fields=(useCaseName;useCaseBoundary;useCasePurpose;useCaseInteraction)>, <crispy_forms.layout.Row object at 0x000001C5BBD2A350>]**

I am not fully sure, but I think field.render in crispy_forms\utils.py at line 66 is getting the form "UseCaseProfileForm".  However, the render_field in crispy_forms\utils.py doc string mention that field is can be a string or a Layout object like `Row`. So, I dont know why the form and layout object are both in the self.field for get_rendered_fields, defined in layouts.py.

**Comment by smithdc1** [comment] 2021-12-31 13:58
`... Layout(self ...`

This looks like your issue to me. `Layout` expects fields (as strings) rather than a form. 🤔

https://django-crispy-forms.readthedocs.io/en/latest/api_layout.html#layout.Layout
