### ISSUE TITLE
Bad usability and errors in the current FileField template for bootstrap4

### ISSUE THREAD

**Issue by nick-traeger** [django-crispy-forms/django-crispy-forms#918] opened 2019-10-23 08:51 UTC
* Package version: 1.8.0
* Django version: 2.2.6
* Python version: 3.6.8
* Template pack: bootstrap4

### Description:

Unfortunately the usability of the FileFields has decreased drastically with the current update, and the behavior is currently incorrect. The label now overlays the current state of the input field, so you can't see if and which file you have selected. Even worse, if a file already exists, the display of the current file and the option to delete it will be hidden.

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [x] Screenshots ![crispy-forms-upload](https://user-images.githubusercontent.com/11520139/67375407-dd5e2900-f582-11e9-8027-61652b5cd3b3.png)
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by carltongibson** [comment] 2019-10-23 09:08
Hi @nick-traeger. Can you provide the generated HTML please? (And what you'd expect would be helpful too.) 

Do you have any customisations in play? (What's your form and helper?)

Thanks.

**Comment by RBDB-001** [comment] 2019-10-23 10:01
I have the same issue. 

<img width="678" alt="Screenshot 2019-10-22 at 17 36 00" src="https://user-images.githubusercontent.com/4265240/67381839-75104700-f584-11e9-97af-cae58b64f472.png">

**Comment by RBDB-001** [comment] 2019-10-23 10:03
Here is the generated HTML. 

<div id="div_id_image" class="form-group"> <label for="id_image" class="">
                Image
            </label> <div class="custom-file ">
    Currently: <a href="/media/company/2019/10/22/Wills_Logo.jpg">company/2019/10/22/Wills_Logo.jpg</a>
<input type="checkbox" name="image-clear" id="image-clear_id">
<label for="image-clear_id">Clear</label><br>
Change:
<input type="file" name="image" accept="image/*" class="clearablefileinput form-control custom-file-input" id="id_image"> <label class="custom-file-label" for="id_image">Choose file</label> <small id="hint_id_image" class="form-text text-muted">Recommended size for logo image is 400px by 400px.</small> </div> </div>

**Comment by RBDB-001** [comment] 2019-10-23 10:04
`<div id="div_id_image" class="form-group"> <label for="id_image" class="">
                Image
            </label> <div class="custom-file ">
    Currently: <a href="/media/company/2019/10/22/Wills_Logo.jpg">company/2019/10/22/Wills_Logo.jpg</a>
<input type="checkbox" name="image-clear" id="image-clear_id">
<label for="image-clear_id">Clear</label><br>
Change:
<input type="file" name="image" accept="image/*" class="clearablefileinput form-control custom-file-input" id="id_image"> <label class="custom-file-label" for="id_image">Choose file</label> <small id="hint_id_image" class="form-text text-muted">Recommended size for logo image is 400px by 400px.</small> </div> </div>`

**Comment by RBDB-001** [comment] 2019-10-23 10:09
If I use dev tools to change the opacity for the file upload field it shows a second field where it should appear in the code but for some reason the custom-file-input is appearing further up the form and obscuring the text that before it. 

<img width="1413" alt="Screenshot 2019-10-23 at 11 05 16" src="https://user-images.githubusercontent.com/4265240/67382333-3a5ade80-f585-11e9-8eca-0578d20c3c60.png">

**Comment by nick-traeger** [comment] 2019-10-23 10:41
I didn't make any changes. Here is a simple sample project and a screenshot as it looks in version 1.7.2.

![crispy-forms-old-upload](https://user-images.githubusercontent.com/11520139/67383979-82333300-f590-11e9-93c1-4eeea6ce43bc.png)

[crispy-forms-test.zip](https://github.com/django-crispy-forms/django-crispy-forms/files/3761802/crispy-forms-test.zip)

New output of the form:
```
<form  method="post"  enctype="multipart/form-data"> <input type="hidden" name="csrfmiddlewaretoken" value="oQCMjyPSQXfaeHW5fV9lP7UHFS8D6C3rM3BkpwB9lEzfwIpM3isyybJxIlyxBOAn"> <div id="div_id_upload" class="form-group"> <label for="id_upload" class=" requiredField">
                Upload<span class="asteriskField">*</span> </label> <div class="custom-file ">
    Currently: <a href="12.pdf">12.pdf</a><br>
Change:
<input type="file" name="upload" class="clearablefileinput form-control custom-file-input" id="id_upload"> <label class="custom-file-label" for="id_upload">Choose file</label> </div> </div> <div class="form-group"> <div class=""> <input type="submit"
    name="submit"
    value="Submit"
    
        class="btn btn-primary"
        id="submit-id-submit"
    
    
    /> </div> </div> </form>
```

Old output of the form:

```
<form  method="post"  enctype="multipart/form-data"> <input type="hidden" name="csrfmiddlewaretoken" value="3SQDex58jZOGmfWtlN59wTJyHR7cPAlFr5PbkvRpOG8LEgpa9aomfXyoKkx6kMSB"> <div id="div_id_upload" class="form-group"> <label for="id_upload" class="col-form-label  requiredField">
                Upload<span class="asteriskField">*</span> </label> <div class="">
                    Currently: <a href="12.pdf">12.pdf</a><br>
Change:
<input type="file" name="upload" class="clearablefileinput" id="id_upload"> </div> </div> <div class="form-group"> <div class=""> <input type="submit"
    name="submit"
    value="Submit"
    
        class="btn btn-primary"
        id="submit-id-submit"
    
    
    /> </div> </div> </form>
```

**Comment by bryan-brancotte** [comment] 2019-10-23 15:16
Hi @nick-traeger 

In 1.8 we used more of the customization provided by bootstrap
https://getbootstrap.com/docs/4.0/components/forms/#file-browser

For the file field, BS4 recommend using JS, a fix can be found at https://stackoverflow.com/a/51497456/2144569

My question @carltongibson is should we add some JS ? and how ?

I will also do a PR so the file field is controled by use_custom_control (cf use_custom_control in https://django-crispy-forms.readthedocs.io/en/latest/form_helper.html#helper-attributes-you-can-set)

**Comment by bryan-brancotte** [comment] 2019-10-23 15:47
In my case, I *only* have the filename not displayed : 
v<1.7
![Capture d’écran de 2019-10-23 17-47-03](https://user-images.githubusercontent.com/11556772/67410954-27fc9700-f5bd-11e9-8c79-f0ff69af6143.png)

v>=1.8

![Capture d’écran de 2019-10-23 17-46-00](https://user-images.githubusercontent.com/11556772/67410912-174c2100-f5bd-11e9-9a3f-25170effa955.png)

**Comment by codetalcott** [comment] 2019-10-23 16:43
Having same problem after updating to v1.8.0, django 2.2.6
File Field continues to show 'Choose file' after selecting file.

**Comment by carltongibson** [comment] 2019-10-23 18:36
OK, so it looks like **without the JavaScript**, the custom form doesn't really work. Is that correct? 

In which case, I think we should probably revert to something that does work in `bootstrap4/layout/field_file.html`, whilst providing docs linking to the BS example, if folks want to create their own template, and JavaScript. 

(Is it really the case that BS4 doesn't provide the JavaScript to go with this? Double checking since it seems... erm... sub-optimal, shall we say...) 

> My question @carltongibson is should we add some JS ? and how ?

_How?_ Well we could use [`Form.Media`](https://docs.djangoproject.com/en/2.2/topics/forms/media), but that's a major change. Maybe we can do that, but not lightly, and not quickly now for a fix.

SO... 

* For now, revert to something that works (as per suggestion above). So make `bootstrap4/layout/field_file.html` something like:

             <div class="{{ field_class }}">	
                {% crispy_field field %}
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            </div>		                

    **For folks needing a fix today**, the quick workaround is to override that template in your project. 

* Later, revisit whether we can ship a functioning version of this, #809 take 2, including the missing JavaScript. 

Make sense? Any thoughts?

**Comment by carltongibson** [comment] 2019-10-23 19:30
The required javascript was pasted on https://github.com/django-crispy-forms/django-crispy-forms/pull/809#issuecomment-461839787

**Comment by bryan-brancotte** [comment] 2019-10-23 19:49
Couldn't we inline the JS right after rendering the field in bootstrap4/layout/field_file.html ? It is kind of hacky but has the advantage of keeping the hack/customization in the template file.

Personally I am not sure to like the idea, I am putting it here to have opinion.

**Comment by carltongibson** [comment] 2019-10-23 20:08
> Couldn't we inline the JS right after rendering the field in bootstrap4/layout/field_file.html ?

But what happens then to the folks who put their JS at the bottom of the page? `$ is undefined`

**Comment by bryan-brancotte** [comment] 2019-10-23 20:24
We can write it in pure JS and put in <script> tag. I will give a try tomorrow on an actual computer.

**Comment by carltongibson** [comment] 2019-10-24 05:57
Hmmm. I still don't think we should ship that, as a new feature, here quickly. Measure twice... and such. 

First off, @nick-traeger and others, does adding the jQuery snippet solve the issue? If so we could document that, in the docs and release notes for 1.8. (Plus "how to fallback", i.e. overriding the template.) 

Then we could think about, say, a custom Layout object here which would encapsulate the required JS, for 1.9 or such.

**Comment by nick-traeger** [comment] 2019-10-24 07:34
Yes, JavaScript works. However, in my opinion this leaves the much bigger problem that the display of the already uploaded file and the deletion of it is not displayed correctly.

**Comment by carltongibson** [comment] 2019-10-24 08:43
OK. Sounds like overriding `file_field.html` as per https://github.com/django-crispy-forms/django-crispy-forms/issues/918#issuecomment-545579556 is the work-around for you for right now.

**Comment by bryan-brancotte** [comment] 2019-10-24 10:37
I agree @carltongibson that I don't want to ship a correction like in a hurry. Maybe we could in a first time for 1.8.1 disable #809, then work for a satisfying solution for a later release ?

**Comment by bryan-brancotte** [comment] 2019-10-24 10:38
@nick-traeger When you talk about the already uploaded file, and deletion, you are talking on using the https://docs.djangoproject.com/fr/2.2/ref/forms/widgets/#django.forms.ClearableFileInput ?

**Comment by nick-traeger** [comment] 2019-10-24 12:44
Yes, that is the widget being used

**Comment by carltongibson** [comment] 2019-10-24 14:52
@bryan-brancotte Yes, that would be my plan. This isn't ready, since what BS4 gives you isn't enough, so it's a bug. Let's fix it _Soon™_, then work on something better at our ease. 👍

**Comment by nick-traeger** [comment] 2019-10-25 07:41
Yes, that resolves the issue!

**Comment by carltongibson** [comment] 2019-10-25 09:15
OK, thanks for the confirmation @nick-traeger. 

We just want to think about whether we can provide an option for folks who have opted into this already, then we'll get that rolled in a do a release. So next week now. 

Thanks for the report, and the involvement in clarify it, and confirming the fix. 👍

**Comment by hazel-james** [comment] 2019-11-17 16:51
Hi, sorry if I'm missing something, but I am (I think?) having the same problem. The "Currently" and "Change" labels are covered, and I can click on both the visible form and in the blank area beneath it to trigger the file upload.

![msedge_O2U8SvmNaL](https://user-images.githubusercontent.com/57199537/69010721-56596200-0930-11ea-93d2-92b24799eb7f.png)

**Comment by smithdc1** [comment] 2019-11-17 17:13
@hazel-james ,

The fix for this was merged into master yesterday. Can you give master a go and us know if you are still seeing the issue?

**Comment by hazel-james** [comment] 2019-11-17 22:35
If the latest is 1.8,0 then that's what I have. I installed using Pip. Do I need to use another method? Thanks!

**Comment by bryan-brancotte** [comment] 2019-11-18 09:27
Hi @hazel-james 
1.8.0 is the latest on pip and indeed have the bug you indicate. As @smithdc1 says, If you install the latest from the repo you will see it fixed:
```
pip install git+https://github.com/django-crispy-forms/django-crispy-forms.git --upgrade
```

Otherwise you can indicate that you don't want 1.8.0 and when 1.8.1 will be released you will have the bugfix:
```
pip install "django-crispy-forms!=1.8.0" --no-cache --upgrade
```

P.S: tested with the MWE of https://github.com/django-crispy-forms/django-crispy-forms/issues/918#issuecomment-545382695

**Comment by smithdc1** [comment] 2019-11-18 18:07
Closing this as the issue is fix for this has been merged into the master branch.

**Comment by bodgerbarnett** [comment] 2020-03-05 12:30
The layout for bootstrap 4 file fields still doesn't show what the value of the field is currently set to, does it? Or have I missed something?

**Comment by codetalcott** [comment] 2020-03-05 20:11
The 1.8.1 release fixed this issue for me.

**Comment by cycleconfident** [comment] 2020-03-06 10:19
I'm using the very latest version - 1.9 - and I still don't see the current value in the widget anywhere.

**Comment by smithdc1** [comment] 2020-03-07 08:21
Here is an example from [crispy-test-project](https://github.com/django-crispy-forms/crispy-test-project) and the latest 1.9.0 release. 

Are you seeing something different? 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39445562/76139747-3b2f7100-604b-11ea-87aa-38de4fa06442.gif)

**Comment by bryan-brancotte** [comment] 2020-03-09 08:23
Hi @codetalcott @cycleconfident @smithdc1 
Correct me If I am wrong: 
 * by default django use a `django.forms.widgets.ClearableFileInput`, a widget with subwidgets which is something we can not, for now, convert the a beautiful BS4 widget.
 * we build the nice BS4 file field iff we use the "simple" `django.forms.widgets.FileInput`, cf example there: https://github.com/django-crispy-forms/crispy-test-project/blob/master/bootstrap4/forms.py#L135

**Comment by smithdc1** [comment] 2020-03-09 08:38
Hi Bryan, hope you are well.

I agree with most of what you say. The piece I've not thought about before is what is the Django standard. 

https://docs.djangoproject.com/en/3.0/ref/models/fields/#filefield

Docs say it is the clearable widget. However I'm not sure quite what this means for us. Do we need to give guidance to over ride default widget etc?

Also filefield and fieldfile means I need more brain power to understand than on my commute :-)

**Comment by bryan-brancotte** [comment] 2020-03-09 13:37
Hi David, fine (and back), hope you the same

I added in the test project a model form with a FileField
![Capture d’écran de 2020-03-09 10-13-03](https://user-images.githubusercontent.com/11556772/76198575-a06f9780-61ee-11ea-9401-238fabd622ab.png)

**Comment by bodgerbarnett** [comment] 2020-03-10 10:17
Just to clarify, the reason for my query was that the widget doesn't show what the file is currently set to (if it has an initial value) - as in the image Bryan has posted before. The value of the field updates properly when you choose a new file but it's just not set when you first see the widget.

**Comment by smithdc1** [comment] 2020-03-10 16:53
@bodgerbarnett super helpful clarification of the issue. Bryan has raised a pull request, any comments you have on that would be valued. 

Bryan, as always, is a few steps ahead of me and I slowly catch up. :smile:

**Comment by bryan-brancotte** [comment] 2020-03-11 08:17
Thanks @smithdc1 but to be honest it is the third (or fourth) time I tried to solve the clearable file field and it is the first time I may have a solution.

Thanks for the feedback ad details @bodgerbarnett, could you please look at https://github.com/django-crispy-forms/django-crispy-forms/pull/1004#issuecomment-597498309 and tell me if, for you, the issue you have would be solved by the rendering the PR propose ? I want to be sure that we are talking about the same issue, and that we are not missing another issue with this widget.

**Comment by bodgerbarnett** [comment] 2020-03-23 15:49
Hi Bryan,

Yes I think that would solve it for me. I guess it's not a very easy field to design and it really doesn't look that great in the "standard" Django version anyway, so the crispy version you've done there looks a lot better.

For now, I've just hacked the current actual image (not the path to the image) into the form field's label, so that the user can see what the image they have set actually looks like, as I don't really think that people care what the name of the file is - they just want to see what the image looks like. But I guess that only applies to ImageFields really.

**Comment by smithdc1** [comment] 2023-02-19 15:00
I think #1004 fixed this. Happy to take another look if I'm missing something!

**Closed by smithdc1** 2023-02-19 15:00 UTC
