### ISSUE TITLE
ModelMultipleChoiceField using CheckboxSelectMultiple performance issue

### ISSUE THREAD

**Issue by strelnikov** [django-crispy-forms/django-crispy-forms#408] opened 2015-02-27 10:50 UTC
guys..for the following form

class UserUnsubscribeForm(forms.Form):
    users = forms.ModelMultipleChoiceField(queryset=User.objects.none())

```
def __init__(self, *args, **kwargs):
    email = kwargs.pop('email')
    super(UserUnsubscribeForm, self).__init__(*args, **kwargs)
    self.fields['users'] = forms.ModelMultipleChoiceField(queryset=User.objects.filter(email=email), widget=forms.CheckboxSelectMultiple)
    # self.fields['users'].widget = forms.CheckboxSelectMultiple()
    # self.fields['users'].queryset = User.objects.filter(email=email)
```

it makes 30 queries for 2 users (result of User.objects.filter(email=email)), or 62 quries for 7 users
if I remove widget, it goes fine just with few queries (up to 5)

in template {% crispy form %}

and also if I will use standard django template {{ form }} everything is ok

**Comment by J3173** [comment] 2015-05-09 19:45
This looks like a duplicate of #303

**Comment by carltongibson** [comment] 2017-02-22 09:23
Duplicate of #303

**Closed by carltongibson** 2017-02-22 09:23 UTC
