### ISSUE TITLE
CRISPY_TEMPLATE_PACK = 'bootstrap4' - results in not being able to click radiobuttons/checkboxes

### ISSUE THREAD

**Issue by allinws** [django-crispy-forms/django-crispy-forms#1202] opened 2022-01-08 14:44 UTC
* Package version: 1.13.0
* Django version: 3.2.9
* Python version: 3.9.0
* Template pack: (Optional)

### Description:

I want to use the following setting:
CRISPY_TEMPLATE_PACK = 'bootstrap4'

However, as soon as I activate it in my settings all radio-buttons and checkboxes are rendered useless as they become impossible to click, when you click on them nothing happens.

### Preferably also include:

- [ ] Example Django Crispy Forms code
```

Settings.py

CRISPY_TEMPLATE_PACK = 'bootstrap4'

```

```
Template.html

{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

    
  <form method="post" enctype="multipart/form-data" id="adForm" data-municipalities-url="{% url 'ajax_load_municipalities' %}" data-areas-url="{% url 'ajax_load_areas' %}" novalidate>
    {% csrf_token %}  

    {% crispy form %}

  </form>
```

```
Forms.py

class NewsEmailForm(forms.ModelForm):

    class Meta:
        model = NewsEmail 
        fields = ('province', 'municipality', 'areas', 'interval', 'ad_type')
        help_texts = {
            'areas': 'Håll in cmd (mac) eller ctrl (windows) för att markera flera',
            'interval': 'Hur ofta du vill få ett mail med nya annonser i valt område.',

        }

    def __init__(self, *args, **kwargs):
        super(NewsEmailForm, self).__init__(*args, **kwargs)
        self.fields['province'].required = True
        self.fields['municipality'].required = True
        self.fields["interval"].choices = list(self.fields["interval"].choices)[1:] 
        self.fields["ad_type"].choices = list(self.fields["ad_type"].choices)[1:] 
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('province', css_class='form-group col-2 mb-0'),
                Column('municipality', css_class='form-group col-2 mb-0 ml-4'),
                Column('areas', css_class='form-group col-3 mb-0 ml-4'),
                Column(
                    InlineRadios('interval'), 
                    css_class='form-group col-1 mb-0 ml-4'
                ),
                Column(
                    InlineRadios('ad_type'), 
                    css_class='form-group col-1 mb-0 ml-4'
                ),
                Column(
                    FormActions(
                        Submit('submit', 'Spara bevakning', css_class='btn btn-sm btn-primary'),
                    ), 
                    css_class='form-group col-1 mt-4 mb-0 ml-4'
                ),
                
            ),
        )
```
- [ ] Screenshots
- [ ] Actual HTML generated

- [ ] Expected HTML

**Comment by smithdc1** [comment] 2022-01-23 20:15
Closing as a duplicate of #1174

**Closed by smithdc1** 2022-01-23 20:15 UTC
