### ISSUE TITLE
Checkbox inputs in CheckBoxSelectMultiple do not render with passed in attrs

### ISSUE THREAD

**Issue by DylanYoung** [django-crispy-forms/django-crispy-forms#746] opened 2017-10-05 13:12 UTC
* Package version: 1.5.2
* Django version: 1.8
* Python version: 2.7.14
* Template pack: bootstrap(2)

### Description:
Checkboxes in CheckBoxSelectMultiple do not render with passed in attrs.

In particular, if trying to render outside a form (with a form attribute), data isn't posted as the field isn't bound to the form.

Minimal Example Form: (must be included on a page with a form called "myform", but outside that forms form tags to see the POST issues, but the generated html should be enough to see what's wrong). 

```
class UserSelectForm(Form):
    selected_users = MultipleChoiceField(
                    choices=[('ex', 'Example'), ('ex2', 'Example2')],
                    initial='ex',
                    widget=CheckboxSelectMultiple(attrs={'form': 'theform'}),
                    required=True)
```

Django's (correct) output:

```
<tr><th><label for="id_selected_users_0">Selected users:</label></th><td><ul id="id_selected_users"><li><label for="id_selected_users_0"><input form="theform" id="id_selected_users_0" name="selected_users" type="checkbox" value="ex" /> Example</label></li>
<li><label for="id_selected_users_1"><input form="theform" id="id_selected_users_1" name="selected_users" type="checkbox" value="ex2" /> Example2</label></li></ul></td></tr>
```

Crispy-form's (incorrect) output:
```
<div id="div_id_selected_users" class="clearfix control-group"> <label for="id_selected_users_0" class="control-label requiredField">
				Selected users<span class="asteriskField">*</span> </label> <div class="controls" > <label class="checkbox"> <input type="checkbox" checked="checked"
                   
                   
                   name="selected_users" id="id_selected_users_1" value="ex"/>
            Example
        </label> <label class="checkbox"> <input type="checkbox" 
                   
                   
                   name="selected_users" id="id_selected_users_2" value="ex2"/>
            Example2
        </label> </div> </div>
```

Interestingly enough, it seems that the passed-in attr isn't rendered in the field at all. 
### Preferably also include:

- [x] Example Django Crispy Forms code
- [ ] Screenshots
- [x] Actual HTML generated
- [x] Expected HTML

**Comment by carltongibson** [comment] 2017-10-17 12:04
I guess this usage is Out of Scope as conceived — rendering the field outside of the form element isn't currently supported. 

I'd happy consider a PR around this, but other than that I'm going to close this as  Out of Scope

**Closed by carltongibson** 2017-10-17 12:04 UTC

**Comment by DylanYoung** [comment] 2017-10-18 20:21
The use case was an EXAMPLE.  The point is that attrs, which are supposed to attach to the relevant form element, DO NOT attach to the relevant form element.

If you need confirmation that it IS BROKEN, look at how a Django CheckBoxSelectMultiple is rendered natively.

If the fact that attrs passed into fields are SUPPOSED to NOT attach to form elements, please point me to the documentation which says this and also explain to me what exactly they ARE for.

**Comment by DylanYoung** [comment] 2017-10-18 20:27
The issue is actually more sever than I've explicitly noted, as you can see in the output above. 

Not only do the `attrs` not attach to the `<input>` element, they ARE NOWHERE in the Fields's rendered output: you've just **silently discarded my data** 👎

**Comment by carltongibson** [comment] 2017-10-19 06:38
Hey @DylanYoung I'm happy to look at this if you can help pin down exactly where the issue is coming up. (I'd guess it's likely a template issue but...)
