### ISSUE TITLE
Labels in radio buttons are clashing with other labels.

### ISSUE THREAD

**Issue by ZzAntares** [django-crispy-forms/django-crispy-forms#624] opened 2016-09-16 05:37 UTC
Hi, I'm having this rendering error in a django form:

![screen shot 2016-09-16 at 00 05 02](https://cloud.githubusercontent.com/assets/3653680/18576172/c4443d2a-7ba4-11e6-8d9c-f40dcc9f6e1a.png)

This error is in 1.5.2 and above, with 1.5.1 the form looks good:

![screen shot 2016-09-16 at 00 31 38](https://cloud.githubusercontent.com/assets/3653680/18576199/f8e271f0-7ba4-11e6-86ee-cecae43af80e.png)

As you can see, the error makes labels clash with next form field, and changes the vertically aligned radio buttons to horizontal.

This is the form:

``` python
class MailServiceRenewalForm(forms.Form):

    SUBSCRIPTION_TYPES = (
        (1, '1 mes'),
        (3, '3 meses'),
        (6, '6 meses'),
        (12, '1 año'),
    )

    PAYMENT_METHODS = (
        ('paypal', 'PayPal'),
        ('cc', 'Credit card'),
    )

    subscription = forms.ChoiceField(
        choices=SUBSCRIPTION_TYPES,
        label='Extender suscripción por',
        widget=forms.RadioSelect,
        required=True)

    coupon = forms.CharField(
        max_length=10,
        label='Cupón de descuento',
        required=False)
```

I'm using this to render the form: `{{ form|crispy }}`. And if I don't use crispy at all (`{{ form }}`) the form will look good as well.

Thanks for the help, I want to use last version since it improves support for Django 1.9.

**Comment by zoidbergwill** [comment] 2016-09-20 20:23
Hi @ZzAntares 

Thanks for the bug report and useful code for reproducing the issue.

Unfortunately I'm unable to reproduce the issue on 1.5.2:

![image](https://cloud.githubusercontent.com/assets/2572493/18687387/268a14ee-7f80-11e6-8377-a6b7f0e3b129.png)

Could you provide the two versions of outputted HTML for that section so we can see what's different?

Which template pack is it, by the way? Just in case I'm using the wrong one.

**Comment by carltongibson** [comment] 2017-02-21 15:53
I'm going to close this since we can't reproduce. Happy to re-open if more detail turns up.

**Closed by carltongibson** 2017-02-21 15:53 UTC
Labels: Bug
