### ISSUE TITLE
ClearableFileInput: too long filenames go to multiple lines out of their area

### ISSUE THREAD

**Issue by cpina** [django-crispy-forms/django-crispy-forms#1028] opened 2020-05-09 13:32 UTC
* Package version: 2ec7b692f948c25917482f0f723b0332acbd809d
* Django version: 3.0.5
* Python version: 2.7.16
* Template pack: (Optional)

### Description:

Using the new ClearableFileInput with a long file name

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [x] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

It generates:
![file-field](https://user-images.githubusercontent.com/489071/81475046-d4286700-9209-11ea-8399-f5a3f9c1c4c3.png)

This is on Firefox 75

Or even:
![Screenshot_20200509_153044](https://user-images.githubusercontent.com/489071/81475083-15b91200-920a-11ea-81fb-3be68bdb7850.png)

If the filenames are too long and can't fit: perhaps they could be displayed only the last N characters with "..." in the beginning?

**Comment by smithdc1** [comment] 2020-05-09 13:43
Super thanks for this. :pray: 

My initial thought was the same, can we chop the file name after so of many characters....

**Comment by cpina** [comment] 2020-05-14 09:47
Backend developer here, not good at all at CSS or Javascript. I had a quick Google and it shows this solution based on CSS:
https://github.com/jasny/bootstrap/issues/263#issuecomment-64007688

I haven't looked at integrating this but it might help to fix this. Any thoughts @smithdc1 or @bryan-brancotte ?

I've just done a quick test using Firefox, F12, select the link and then edited the CSS (as I think that I'm missing a class to apply it from my css.css) and I had to add padding-right: 100px; in order to have the Clear checkbox. Example:

![Screenshot_20200514_114601](https://user-images.githubusercontent.com/489071/81919738-854b4a80-95d8-11ea-847a-9ba28998f1c8.png)

**Comment by bryan-brancotte** [comment] 2020-05-18 13:24
Hi @cpina ,

### Reproducing bug

Indeed the graphical bug is unpleasant, but I am not able to reproduce it. I see other bug/rendering : 

with Firefox 76.0.1 (64 bits)
![Capture d’écran de 2020-05-18 14-59-10](https://user-images.githubusercontent.com/11556772/82215778-2fe4a580-9918-11ea-867b-4deaa6566f64.png)

with Chrome Version 81.0.4044.129 (Build officiel) (64 bits)
![Capture d’écran de 2020-05-18 14-59-20](https://user-images.githubusercontent.com/11556772/82215817-3d019480-9918-11ea-8ca2-236ff644d954.png)

The screenshots have been made with https://github.com/django-crispy-forms/crispy-test-project.

### Discussion

Cutting the end of the path for the "Currently" field makes impossible to read the whole path at once, but preserve graphical placement. A user has to hover the link to read the whole path.

Cutting the end of the "Change" value makes impossible for the user to check what file have been chosen. Also it is a Bootstrap bug, so indeed it is unpleasant, but at least it is coherent with other system using bootstrap.

In the end I think end should not be chopped. As a middle ground maybe each box should grow to follow their content, at least for the "Change" part ( and I haven't find how yet).

What do you think of the alternative solution @cpina ?

P.S: for the "Currently" we just have to add a `word-break: break-word;` to the span that contains the link
```html
<span style="flex-grow: 1;word-break: break-word;">
    <a href="./somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-.txt">
./somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/somedire/myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-myfile-.txt
    </a>
</span>
```

**Comment by cpina** [comment] 2020-05-18 16:13
My screenshots were based on one of my projects and maybe, for some reason it behaves differently. Sorry for the noise.

I also thought that it was not nice that my "patch" was hiding the end of the paths as it would hide files to the user. Perhaps, if this route was chosen, a tooltip would help so a user could see the files leaving the pointer there. I haven't tested this and I don't know if it's possible.

I have one more thing to put on the table: if we had a "class='something'" in the span for these fields django-crispy-forms users would be able to tweak this easier using their own CSS. Specially since different people might prefer different workarounds or solutions.

Answering:
> In the end I think end should not be chopped. As a middle ground maybe each box should grow to follow their content, at least for the "Change" part ( and I haven't find how yet).

Yes for this! (no idea either how to grow it following its content)

And for the "Currently" section not growing for me: I'll test with the https://github.com/django-crispy-forms/crispy-test-project and I'll try to compare with the project that I'm working on.

Thanks very much for looking at this; and for improving the file field in first instance!

**Comment by cpina** [comment] 2020-06-05 15:38
Hi @bryan-brancotte  and others - I've finally had some time to investigate this a bit more and now I know why in my project the FileField filename goes out of the box (see my screenshots) but not in the crispy-test-project.

In my project I use Bootstrap 4.4.1 and crispy-test-project uses Bootstrap 4.0.0. Updating Bootstrap of the crispy-test-project to 4.5.0 (or 4.4.1) it has the same problem as my project. Or, downgrading my project's Bootstrap to 4.0.0 then it works (I don't really want to do this).

I've opened a PR to update Bootstrap in the test project: https://github.com/django-crispy-forms/crispy-test-project/pull/19

Then, hopefully, you should see the "broken" UI.
Tests with Firefox 77.0.1 and I see that Bootstrap 4.5.0 and the crispy-test-project with Chromium 80.0.3987.162 is also broken.

I haven't investigated more at the moment.

**Comment by cpina** [comment] 2020-06-05 15:43
I'm just searching issues/PRs in Bootstrap. This might be related:
https://github.com/twbs/bootstrap/issues/30438
https://github.com/twbs/bootstrap/pull/30699

But I'm not 100%. I only had a very quick look.

**Comment by bryan-brancotte** [comment] 2020-06-08 10:58
Hi @cpina

Thanks for django-crispy-forms/crispy-test-project#19 I've merged it.

twbs/bootstrap#30699 is related to BootStrap V5, but the issue is indeed around the height of the .form-control.

I have pushed the changes we talked earlier on your branch (not chopping the current filename, and having an auto height). Is it fixing your problem @cpina ?

**Comment by bryan-brancotte** [comment] 2020-06-08 10:59
Hi @cpina and @smithdc1 

When changing to a new filename, I hesitate between chopping the new filename (avoid to overflow over other elements, and better rendering) and keeping it (more information to the user). @smithdc1 are you still pro-chop since [this comment](https://github.com/django-crispy-forms/django-crispy-forms/issues/1028#issuecomment-626178290) ? I am kind of pro-chop, but really unsure.

**Comment by cpina** [comment] 2020-06-08 11:34
@bryan-brancotte : I've just tried it with (in my requirements.txt, in case that someone wants to play with the example project):

`-e git://github.com/cpina/django-crispy-forms.git@f3c8db75a065810ba716990c05fc60245d8279ef#egg=django_crispy_forms`

And the currently in my project it looks fantastic! thanks for all of this!

The "Change" and just to help @smithdc1 and confirm that you expected this looks like:
![file-field-currently](https://user-images.githubusercontent.com/489071/84025747-64360980-a98c-11ea-93ae-7d51eb5439b4.png)

Hovering the "Change" shows the full file name in a tooltip.

**Comment by bryan-brancotte** [comment] 2020-06-08 11:46
I forgot about the hovering that let you know the whole new file name. I am pro chopping for the second part.

@cpina I have also used a bootstrap4 class for the ellipsis

**Comment by smithdc1** [comment] 2020-06-08 11:56
Both - great work :-)

I'm +1 on ellipsis. 

I may have missed something.... What happened the the 'clear' checkbox? It is missing from recent images?

**Comment by cpina** [comment] 2020-06-08 12:02
> Both - great work :-)

Very quick answer...

> I'm +1 on ellipsis.

I think that I'm +1 on ellipsis as well, if possible

> I may have missed something.... What happened the the 'clear' checkbox? It is missing from recent images?

My last screenshots are from a FileField with `blank=True`. The no clear checkbox appears (which is correct)

**Comment by smithdc1** [comment] 2020-07-28 20:54
@cpina I'm assuming we can close this now. Shout if you disagree.

**Closed by smithdc1** 2020-07-28 20:54 UTC
