### ISSUE TITLE
include_media VariableDoesNotExist

### ISSUE THREAD

**Issue by chr1s3sw0rthy** [django-crispy-forms/django-crispy-forms#863] opened 2019-03-28 09:39 UTC
* Package version: 1,7,2
* Django version: 2.0.13
* Python version: 3.5.3
* Template pack: (Optional)

### Description:

Installed several versions of Cookiecutter-Django form pydanny and have the same issue with all. Putting this issue here as it seems to be a crispy issue.

I consistently get:

Exception has occurred: VariableDoesNotExist
Failed lookup for key [include_media] .....

when running the code. 

I can modify the html from {{ form|crispy }} to {{form}} and the issue does not occur. Of course, the form does not look crispy.

The error shows uni_form.html

### Preferably also include:

- [ ] Example Django Crispy Forms code

{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block inner %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form|crispy }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction btn btn-primary" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

- [ ] Screenshots
- [ ] Actual HTML generated

{% load crispy_forms_utils %}

{% specialspaceless %}
    {% if include_media %}{{ form.media }}{% endif %}

.......

Error Message:

Exception has occurred: VariableDoesNotExist
Failed lookup for key [include_media] in [{'None': None, 'False': False, 'True': True}, {'False': False, 'None': None, 'form': <LoginForm bound=False, valid=Unknown, fields=(login;password;remember)>, 'field_class': '', 'True': True, 'form_show_labels': True, 'form_show_errors': True, 'label_class': ''}]
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/defaulttags.py", line 880, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/defaulttags.py", line 307, in render
    match = condition.eval(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/crispy_forms/templatetags/crispy_forms_utils.py", line 34, in render
    return remove_spaces(self.nodelist.render(context).strip())
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chrisesworthy/code/Acuity/acuity_env/lib/python3.5/site-packages/crispy_forms/templatetags/crispy_forms_filters.py", line 66, in as_crispy_form

- [ ] Expected HTML

**Comment by pymike00** [comment] 2019-03-28 10:53
I experience the same error as above, with:

Python 3.7.2
Django 2.1.7
django-crispy-forms 1.7.2

running from Linux Manjaro 18.0.4


**However in my case the problem only manifests itself when running Django's development server from Visual Studio Code Debugging Tool with the Python Extension version 2019.3.6139**, with such configuration, as you can see only "--nothreading" is disabled, as usual, because I am using Chrome:

```
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload",
                // "--nothreading",
            ],
            "django": true
        },
```

The problem **does not** manifest itself when running the development server from a standard shell with the command "manage.py runserver", nor it manifests itself using a previous version of the Python Extension discussed above, such as version 2019.2.5558.

Do you happen to be using VS Code as well, @chr1s3sw0rthy ?

**Comment by chr1s3sw0rthy** [comment] 2019-03-28 11:26
Yes - VSCode running the same way that you are. I commented out nothreading, etc.

As my work around, I changed {{ form|crispy }} to {{ form }} and that ran fine.

I just put |crispy and ran it with manage.py runserver. I get the expected behavior like you did.

I can confirm your results. Im do not know if the issue is with the extension or crispy forms. Im going to manage.py runserver for now.

Thank you.

**Comment by chr1s3sw0rthy** [comment] 2019-03-28 11:43
I was able to get the Python extension to work (i.e. starting the server in Debug) with the config in launch.json.

        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/acuity/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
###     **//          "--noreload",**
    //          "--nothreading"
            ],
            "django": true
        },

**Comment by pymike00** [comment] 2019-03-28 12:13
Commenting "--noreload" seems to work fine but if you stop the dev server it will in fact not stop!

Running it again I get: **Error: That port is already in use.**

I have opened a proper issue in the Python Extension Repo https://github.com/Microsoft/vscode-python/issues/4988

**Comment by carltongibson** [comment] 2019-03-28 12:51
Thanks for the input both. 

@qubitron it might be worth you looking at this. [`VariableDoesNotExist` gets thrown when looking up the variable](https://github.com/django/django/blob/5a92bb0725e07068b260364ef66466f126000b0b/django/template/base.py#L816) I guess the debugger is just being a little aggressive... (???)

**Comment by carltongibson** [comment] 2019-03-28 13:20
(Closing this since it's not a crispy forms issue...)

**Closed by carltongibson** 2019-03-28 13:20 UTC

**Comment by chr1s3sw0rthy** [comment] 2019-03-28 14:06
> Commenting "--noreload" seems to work fine but if you stop the dev server it will in fact not stop!
> 
> Running it again I get: **Error: That port is already in use.**
> 
> I have opened a proper issue in the Python Extension Repo [Microsoft/vscode-python#4988](https://github.com/Microsoft/vscode-python/issues/4988)

I see that same behavior.

**Comment by qubitron** [comment] 2019-03-29 00:32
@carltongibson we're tracking the issue here: https://github.com/Microsoft/ptvsd/issues/1276

The Python extension's debugger currently doesn't support auto-reload well, and if you run Django without --noreload the issue is that auto-reload creates multiple Django processes which the Python extension doesn't know about and so they don't get killed when you stop debugging. Not sure why running with --noreload causes an exception, if you run python manage.py runserver --noreload do you get the same exception?

**Comment by pymike00** [comment] 2019-03-29 11:54
> @carltongibson we're tracking the issue here: [Microsoft/ptvsd#1276](https://github.com/Microsoft/ptvsd/issues/1276)
> 
Not sure why running with --noreload causes an exception, if you run python manage.py runserver --noreload do you get the same exception?

No, running with --noreload causes no exception at all, on the contrary it works with the limitations you are referencing! (i.e. Python extension can't manage all the processes)

A quick fix to the problem here has been found, by setting django = false in launch.json, here https://github.com/Microsoft/vscode-python/issues/4988#issuecomment-477601737


p.s. I think also it's important to point out that I have always been commenting out "--no-threading" because of the Chromium bug referenced in VS Code documentation, way before Python Extension version 2019.3.6139 came out. So that is not something done while trying to find a quick fix to the Debugger's problem.

**Comment by pymike00** [comment] 2019-03-29 12:06
> @carltongibson we're tracking the issue here: [Microsoft/ptvsd#1276](https://github.com/Microsoft/ptvsd/issues/1276)
> 
> The Python extension's debugger currently doesn't support auto-reload well, and if you run Django without --noreload the issue is that auto-reload creates multiple Django processes which the Python extension doesn't know about and so they don't get killed when you stop debugging. Not sure why running with --noreload causes an exception, if you run python manage.py runserver --noreload do you get the same exception?

No, running python manage.py runserver --noreload causes no exception, the problem only manifests itself when using the Debugger!
