### ISSUE TITLE
Checkbox select multiple generates a lot of queries.

### ISSUE THREAD

**Issue by pypetey** [django-crispy-forms/django-crispy-forms#357] opened 2014-08-17 08:06 UTC
Hey!

I've discovered a bug where field which has ModelChoiceField widget generates a lot of queries. 
It evaluates queryset for each generated option.

It's done probably by crispy_forms/utils.py -> render_field

location = forms.ModelChoiceField(queryset=Place.objects.none(), widget=forms.CheckboxSelectMultiple(),
                                      empty_label=None, required=False)
        self.fields['location'].queryset = Place.objects.filter(type=Place.TOWN).annotate(advert_count=Count("adverts"))

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html

It did not hit the database so often when I used django forms.

**Comment by carltongibson** [comment] 2017-02-22 08:39
Closing as duplicate of #303

**Closed by carltongibson** 2017-02-22 08:39 UTC
