### ISSUE TITLE
1.12.0 Release broke radio buttons, check boxes

### ISSUE THREAD

**Issue by DanielSwain** [django-crispy-forms/django-crispy-forms#1174] opened 2021-06-23 15:31 UTC
* Package version:  1.12.0
* Django version:  3.2.4
* Python version:  3.8.5
* Template pack: Bootstrap 4

**Description:**  Upgrading to 1.12.0 broke all radio buttons and checkboxes on a previously working site.  I have confirmed that the 1.12.0 release is where the bug was introduced by stepping back to 1.11 and then updating to 1.11.2 with all still working at 1.11.2.  Looking at the HTML, it looks like the problem is that there are no IDs on the `<input>`s and only a `for` with no `=some_id` on the `<label>` corresponding to the `<input>`.

Following are screenshots of one of the fields on the rendered form, the HTML, and the Crispy Forms Python code:

![image](https://user-images.githubusercontent.com/7819909/123123671-02203900-d415-11eb-817b-2e952b7c7f65.png)

![image](https://user-images.githubusercontent.com/7819909/123124893-0f89f300-d416-11eb-8373-c149582b563b.png)

![image](https://user-images.githubusercontent.com/7819909/123124805-fda85000-d415-11eb-8ce1-9f92aaa4d2c3.png)

**Comment by smithdc1** [comment] 2021-06-23 16:32
Thanks for the report. 

When testing using the [crispy-test-project](https://github.com/django-crispy-forms/crispy-test-project) rendering radios/checboxes works for me. Here's what I get when rendering `InlineRadios`. The `for` and `id` is correctly rendered and we see similar results in the [tests](https://github.com/django-crispy-forms/django-crispy-forms/blob/main/crispy_forms/tests/results/bootstrap4/test_layout/test_use_custom_control_is_used_in_radio_true.html). :thinking:

I need more help trying to replicate the issue. Would you be able to share a small test project showing the issue? 

```html
<div id="div_id_default_form-inline_radio_buttons" class="form-group"> 
    <label class=" requiredField">Inline radio buttons<span class="asteriskField">*</span> </label> 
<div> 
<div class="custom-control custom-radio custom-control-inline"> 
    <input type="radio" class="custom-control-input" name="default_form-inline_radio_buttons" value="option_one" id="id_default_form-inline_radio_buttons_0" required> 
    <label class="custom-control-label" for="id_default_form-inline_radio_buttons_0">option_one</label> 
</div> 
<div class="custom-control custom-radio custom-control-inline"> 
    <input type="radio" class="custom-control-input" name="default_form-inline_radio_buttons" value="option_two" id="id_default_form-inline_radio_buttons_1" required checked> 
    <label class="custom-control-label" for="id_default_form-inline_radio_buttons_1">option_two</label> 
</div> 
<small id="hint_id_default_form-inline_radio_buttons" class="form-text text-muted">help on a inline_radio_buttons</small> 
```

**Comment by nick-traeger** [comment] 2021-06-25 14:37
We have the same problem and it can be reproduced by applying InlineRadios to a ChoiceField that does not use widget=forms.RadioSelect. Also, the current selection is then marked by selected instead of checked.

**Comment by smithdc1** [comment] 2021-06-25 17:33
> InlineRadios to a ChoiceField that does not use widget=forms.RadioSelect. 

Thanks for the report. 👍

Clearly we didn't have coverage for rendering select widgets as radios. 

Also the docs say that the widget should be set to `forms.RadioSelect`. (This isn't a recent change, they've 'always' said this)

> It renders a Django forms.ChoiceField field with its widget set to forms.RadioSelect using inline radio button

I'll have a look, but my initial gut reaction is that while this worked it wasn't the intention / supported behaviour. 🤔 Maybe we could beef up the release notes.

**Comment by borwickatuw** [comment] 2021-07-03 00:01
FYI this broke for me as well.

Here is pseudo-code for what broke:
```
class ExampleModel(models.Model):
    yes_no = models.ChoiceField(
        choices=(('Y', 'Yes'),
                 ('N', 'No')),
        max_length=1)


def upgrade_formfield_callback(field, **kwargs):
    form_field = field.formfield(**kwargs)

    if hasattr(field, 'choices') and field.choices \
        and len(field.choices)>0 and len(field.choices)<11:
        form_field.widget = RadioSelect(**kwargs)

    return form_field


class ExampleForm(ModelForm):
    formfield_callback = upgrade_formfield_callback

    class Meta:
    	  model = ExampleModel
```


Here's how I got the code to work:
```
        form_field.widget = RadioSelect(choices=form_field.choices,
                                        **kwargs)
```

(I populated the choices attribute.)

**Comment by serl** [comment] 2021-08-03 08:03
Hello, broken for me as well, using InlineRadios directly on a model field having `choices`.
As a fix I downgraded to 0.11.2 😄

Would it be difficult to support the old behavior? Or at least raise an exception for the bogus usage..?

**Comment by radusuciu** [comment] 2021-12-10 22:22
I'm encountering this same issue when rendering a djang-filter ModelMultipleChoiceFilter to checkboxes. I don't have that much crispy forms experience but I think that the issue is here:

```html
<input type="checkbox" class="{%if use_custom_control%}custom-control-input{% else %}form-check-input{% endif %}{% if field.errors %} is-invalid{% endif %}" name="{{ field.html_name }}" value="{{ option.value|unlocalize }}" {% include "bootstrap4/layout/attrs.html" with widget=option %}>
<label class="{%if use_custom_control%}custom-control-label{% else %}form-check-label{% endif %}" for="{{ option.attrs.id }}">
    {{ option.label|unlocalize }}
</label>
```
https://github.com/smithdc1/django-crispy-forms/blob/5e87e379f953feedef2f5ff76d0398e1adf35380/crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html#L10-L13

What strikes me as odd is that while the `label` has a `for` attribute (`for="{{ option.attrs.id }}"`), the `input` does not have a corresponding `id`. Compare this to the code from the previous revision:

https://github.com/smithdc1/django-crispy-forms/blob/79714a66e4be5ea15a560073df6ebdd0cf0e8926/crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html#L8-L11
```html
<input type="checkbox" class="{%if use_custom_control%}custom-control-input{% else %}form-check-input{% endif %}{% if field.errors %} is-invalid{% endif %}"{% if choice.0 in field.value or choice.0|stringformat:"s" in field.value or choice.0|stringformat:"s" == field.value|default_if_none:""|stringformat:"s" %} checked{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter0 }}" value="{{ choice.0|unlocalize }}" {% if field.field.disabled %}disabled="true"{% endif %} {{ field.field.widget.attrs|flatatt }}>
<label class="{%if use_custom_control%}custom-control-label{% else %}form-check-label{% endif %}" for="id_{{ field.html_name }}_{{ forloop.counter0 }}">
    {{ choice.1|unlocalize }}
</label>
```

Notice that on the `input` we have `id="id_{{ field.html_name }}_{{ forloop.counter0 }}"`, and on the `label`: `for="id_{{ field.html_name }}_{{ forloop.counter0 }}"`

So it seems that we've moved from automatically generated and matching `id`/`for` attributes to a configurable `for` attribute and no `id` attribute. I believe that this is a mistake and can submit a PR to address this.

**Comment by allinws** [comment] 2022-01-08 14:50
Also have this issue, opened a new issue as it don't seem to have been fixed in over 6 months.

https://github.com/django-crispy-forms/django-crispy-forms/issues/1202

**Comment by radusuciu** [comment] 2022-01-08 16:38
> Also have this issue, opened a new issue as it don't seem to have been fixed in over 6 months.
> 
> #1202

Have you tried explicitly setting the `widget` parameter in your filter definition to whatever is appropriate? eg. `forms.CheckboxSelectMultiple`

**Comment by dfrankow** [comment] 2022-03-29 19:30
FYI for others who come here, [this comment](https://github.com/django-crispy-forms/django-crispy-forms/issues/1174#issuecomment-868724869) has another workaround:

> Also the docs say that the widget should be set to forms.RadioSelect.

So if you set your widget to forms.RadioSelect, it'll work.

**Comment by smithdc1** [comment] 2022-05-22 16:09
Hi all 👋 

So it seems that we've found the source of the issue and crispy-forms continues to behave as documented even if there was a bug in previous versions that meant a different behaviour could also be achieved. 

On that basis I'm going to close this as I don't think there's anything else we should do here. Maybe we can document better but happy to take feedback on this point. 🙏

(I wonder if folk will find this with a Web search now in any case).

Thanks again for all of your input and feedback. 🎁

**Closed** 2022-05-22 16:10 UTC

**Comment by spapas** [comment] 2023-08-04 09:11
Hello friends, unfortunately I also stumbled upon this issue on django-crispy-forms==2.0. The correct solution is the one @borwickatuw described [above](https://github.com/django-crispy-forms/django-crispy-forms/issues/1174#issuecomment-873309379).
