### ISSUE TITLE
How can i do a "UneditableField" field with no validation for required fields?

### ISSUE THREAD

**Issue by heliogutierrez** [django-crispy-forms/django-crispy-forms#341] opened 2014-06-25 19:24 UTC
I have the next model form:

```
class EstatusForm(forms.ModelForm):    

    def __init__(self, *args, **kwargs):
        super(EstatusForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'estatus_update'
        self.helper.form_class = 'form-inline'
        self.helper.layout = Layout(
            Row(UneditableField('code', readonly=True),
                UneditableField('orderdate', readonly=True),                            
                ),
            Row(UneditableField('bpartner', readonly=True),
                UneditableField('type_owner', readonly=True),
                UneditableField('policy_type', readonly=True),                
            ),
            Row('status',
                Field('requesteddate', css_id='requesteddate'),
                Field('finisheddate', css_id='finisheddate'),
            ),            
            Row(
                Submit('submit', 'Save', css_class='btn btn-primary'),                            
                Reset('clean', 'Clean',css_class='btn btn-warning'),
                Button('cancel', 'Cancel', onclick='history.go(-1);', css_class="btn-danger"),
                css_class="form-actions form-custom"                
            )

        )      
    class Meta:
        model=Rekuest
```

and the fields it show as read only and its ok, but when i click on Save button, show error message because i don't typed any data in required fields and this fields are as read only.

I want to show all fields but only validate the enabled fields.

Any sugerence?

**Comment by carltongibson** [comment] 2017-02-22 08:22
Closing as duplicate of #326, to be handled by #576

**Closed by carltongibson** 2017-02-22 08:22 UTC
